default:
  target: snowflake
  outputs:
    snowflake:
      account: ''
      user: ''
      database: ANALYTICS_DEV
      type: snowflake
      schema: DBT_CESTRADA_DEV
      threads: 4
      role: ANALYST
      warehouse: COMPUTE_WH