# Reference this view as analytics_dev_dbt_cestrada_dev__product_images
catalog: ANALYTICS_DEV
schema: DBT_CESTRADA_DEV
table_name: PRODUCT_IMAGES

dimensions:
  id:
    sql: '"ID"'
    format: ID
    primary_key: true

  image:
    sql: '"IMAGE"'

measures:
  count:
    aggregate_type: count
