WITH PARAMS AS (
  SELECT 
    CURRENT_DATE() AS AS_OF_DATE,
    (YEAR(CURRENT_DATE()) - 2025) AS YEAR_OFFSET 
),

BASE_OPPS AS (
  /* Retrieve the base opportunity records and calculate shifted dates */
  SELECT 
    O.*,
    DATEADD(MONTH, P.YEAR_OFFSET * 12, O.CREATED_DATE)            AS SHIFTED_CREATED_DATE,
    DATEADD(MONTH, P.YEAR_OFFSET * 12, O.CLOSE_DATE)              AS SHIFTED_CLOSE_DATE,
    DATEADD(MONTH, P.YEAR_OFFSET * 12, O.LAST_STAGE_CHANGE_DATE)  AS SHIFTED_LAST_STAGE_CHANGE_DATE,
    DATEADD(MONTH, P.YEAR_OFFSET * 12, O.FIRST_DEMO_DATE)         AS SHIFTED_FIRST_DEMO_DATE,
    DATEADD(MONTH, P.YEAR_OFFSET * 12, O.TRIAL_START_DATE)        AS SHIFTED_TRIAL_START_DATE
  FROM {{ ref('stg_saas__opportunities')}} O
  CROSS JOIN PARAMS P
  WHERE DATEADD(MONTH, P.YEAR_OFFSET * 12, O.CREATED_DATE) <= P.AS_OF_DATE
),

LATEST_HIST AS (
  /* Find the most recent historical record for each opportunity */
  SELECT * FROM (
    SELECT
      OH.OPPORTUNITY_ID,
      OH.NAME, 
      OH.STAGE_NAME, 
      OH.AMOUNT, 
      OH.PROBABILITY, 
      OH.TYPE,
      OH.NEXT_STEPS, 
      OH.LEAD_SOURCE, 
      OH.IS_WON, 
      OH.FORECAST_CATEGORY,
      OH.OWNER_ID, 
      OH.SALES_ENGINEER_ID, 
      OH.CONTACT_ID, 
      OH.COMPETITOR, 
      OH.LOSS_REASON,
      OH.WIN_REASON,
      OH.RISK_SCORE,
      OH.RISK_FLAGS,
      -- New Fields (Consolidated Risk)
      OH.IDENTIFIED_PAIN,
      OH.RISK_DETAILS,
      OH.AE_NOTES,
      DATEADD(MONTH, P.YEAR_OFFSET * 12, OH.CREATED_DATE)            AS SHIFTED_HIST_CREATED_DATE,
      DATEADD(MONTH, P.YEAR_OFFSET * 12, OH.CLOSE_DATE)              AS SHIFTED_HIST_CLOSE_DATE,
      DATEADD(MONTH, P.YEAR_OFFSET * 12, OH.LAST_STAGE_CHANGE_DATE)  AS SHIFTED_HIST_LAST_STAGE_CHANGE_DATE,
      DATEADD(MONTH, P.YEAR_OFFSET * 12, OH.FIRST_DEMO_DATE)         AS SHIFTED_HIST_FIRST_DEMO_DATE,
      DATEADD(MONTH, P.YEAR_OFFSET * 12, OH.TRIAL_START_DATE)        AS SHIFTED_HIST_TRIAL_START_DATE,
      ROW_NUMBER() OVER (
        PARTITION BY OH.OPPORTUNITY_ID
        ORDER BY OH.LAST_STAGE_CHANGE_DATE DESC 
      ) AS RN
    FROM {{ ref('stg_saas__opportunity_history') }} OH
    CROSS JOIN PARAMS P
    WHERE DATEADD(MONTH, P.YEAR_OFFSET * 12, OH.LAST_STAGE_CHANGE_DATE) <= P.AS_OF_DATE
  ) WHERE RN = 1
),

CLOSED_ASOF AS (
  /* Records that were already closed as of the point-in-time date */
  SELECT
    ID, 
    ACCOUNT_ID, 
    NAME, 
    STAGE_NAME, 
    AMOUNT, 
    ARR, 
    ACV, 
    TCV, 
    CONTRACT_TERM_MONTHS,
    PROBABILITY,
    SHIFTED_CLOSE_DATE AS CLOSE_DATE,
    TYPE, 
    NEXT_STEPS, 
    LEAD_SOURCE, 
    IS_WON, 
    FORECAST_CATEGORY,
    OWNER_ID, 
    SALES_ENGINEER_ID, 
    SHIFTED_CREATED_DATE AS CREATED_DATE,
    CONTACT_ID, 
    SHIFTED_LAST_STAGE_CHANGE_DATE AS LAST_STAGE_CHANGE_DATE,
    SHIFTED_FIRST_DEMO_DATE AS FIRST_DEMO_DATE,
    SHIFTED_TRIAL_START_DATE AS TRIAL_START_DATE,
    COMPETITOR, 
    LOSS_REASON,
    WIN_REASON,
    RISK_SCORE,
    RISK_FLAGS,
    -- New Fields (Consolidated Risk)
    IDENTIFIED_PAIN,
    RISK_DETAILS,
    AE_NOTES
  FROM BASE_OPPS
  CROSS JOIN PARAMS P
  WHERE SHIFTED_CLOSE_DATE IS NOT NULL AND SHIFTED_CLOSE_DATE < P.AS_OF_DATE
),

OPEN_ASOF_OVERLAY AS (
  /* Records that were open as of the point-in-time date (with historical overlay) */
  SELECT
    O.ID,
    O.ACCOUNT_ID,
    COALESCE(H.NAME,               O.NAME)               AS NAME,
    COALESCE(H.STAGE_NAME,         O.STAGE_NAME)         AS STAGE_NAME,
    COALESCE(H.AMOUNT,             O.AMOUNT)             AS AMOUNT,
    O.ARR, 
    O.ACV, 
    O.TCV, 
    O.CONTRACT_TERM_MONTHS,
    COALESCE(H.PROBABILITY,        O.PROBABILITY)        AS PROBABILITY,
    COALESCE(H.SHIFTED_HIST_CLOSE_DATE, O.SHIFTED_CLOSE_DATE) AS CLOSE_DATE,
    COALESCE(H.TYPE,               O.TYPE)               AS TYPE,
    COALESCE(H.NEXT_STEPS,         O.NEXT_STEPS)         AS NEXT_STEPS,
    COALESCE(H.LEAD_SOURCE,        O.LEAD_SOURCE)        AS LEAD_SOURCE,
    COALESCE(H.IS_WON,             O.IS_WON)             AS IS_WON,
    COALESCE(H.FORECAST_CATEGORY,  O.FORECAST_CATEGORY)  AS FORECAST_CATEGORY,
    COALESCE(H.OWNER_ID,           O.OWNER_ID)           AS OWNER_ID,
    COALESCE(H.SALES_ENGINEER_ID,  O.SALES_ENGINEER_ID)  AS SALES_ENGINEER_ID,
    O.SHIFTED_CREATED_DATE                                 AS CREATED_DATE,
    COALESCE(H.CONTACT_ID,         O.CONTACT_ID)         AS CONTACT_ID,
    COALESCE(H.SHIFTED_HIST_LAST_STAGE_CHANGE_DATE, O.SHIFTED_LAST_STAGE_CHANGE_DATE) AS LAST_STAGE_CHANGE_DATE,
    COALESCE(H.SHIFTED_HIST_FIRST_DEMO_DATE,        O.SHIFTED_FIRST_DEMO_DATE)        AS FIRST_DEMO_DATE,
    COALESCE(H.SHIFTED_HIST_TRIAL_START_DATE,       O.SHIFTED_TRIAL_START_DATE)       AS TRIAL_START_DATE,
    COALESCE(H.COMPETITOR,         O.COMPETITOR)         AS COMPETITOR,
    COALESCE(H.LOSS_REASON,        O.LOSS_REASON)        AS LOSS_REASON,
    COALESCE(H.WIN_REASON,         O.WIN_REASON)         AS WIN_REASON,
    COALESCE(H.RISK_SCORE,         O.RISK_SCORE)         AS RISK_SCORE,
    COALESCE(H.RISK_FLAGS,         O.RISK_FLAGS)         AS RISK_FLAGS,
    -- New Fields with Historical Overlay logic
    COALESCE(H.IDENTIFIED_PAIN,    O.IDENTIFIED_PAIN)    AS IDENTIFIED_PAIN,
    COALESCE(H.RISK_DETAILS,       O.RISK_DETAILS)       AS RISK_DETAILS,
    COALESCE(H.AE_NOTES,           O.AE_NOTES)           AS AE_NOTES
  FROM BASE_OPPS O
  CROSS JOIN PARAMS P
  LEFT JOIN LATEST_HIST H ON H.OPPORTUNITY_ID = O.ID
  WHERE (O.SHIFTED_CLOSE_DATE IS NULL OR O.SHIFTED_CLOSE_DATE >= P.AS_OF_DATE)
)

SELECT * FROM CLOSED_ASOF
UNION ALL
SELECT * FROM OPEN_ASOF_OVERLAY
ORDER BY CREATED_DATE DESC