with base as (
  select * from {{ ref('stg_pharma__fact_claim') }}
),
anchor as (
  select max(CLAIMDATE) as anchor_date from base
)
select
  t.CLAIMID as CLAIMID,
  t.PHYSICIANID as PHYSICIANID,
  t.PRODUCTID as PRODUCTID,
  t.MARKETID as MARKETID,
  t.PATIENTDEIDENTIFIEDID as PATIENTDEIDENTIFIEDID,
  {{ pharma_shift_date('t.CLAIMDATE', 'anchor.anchor_date') }} as CLAIMDATE,
  t.CLAIMTYPE as CLAIMTYPE,
  t.PAYER as PAYER,
  t.PAYERTYPE as PAYERTYPE,
  t.PAYERREGION as PAYERREGION,
  t.CLAIMSTATUS as CLAIMSTATUS,
  t.DAYSSUPPLY as DAYSSUPPLY,
  t.QUANTITY as QUANTITY,
  t.AMOUNTBILLED as AMOUNTBILLED,
  t.AMOUNTPAID as AMOUNTPAID,
  t.FORMULARYTIER as FORMULARYTIER,
  t.PRIORAUTHREQUIRED as PRIORAUTHREQUIRED,
  t.STEPTHERAPYREQUIRED as STEPTHERAPYREQUIRED,
  t.QUANTITYLIMIT as QUANTITYLIMIT,
  t.REBATEELIGIBLE as REBATEELIGIBLE,
  t.COPAYAMOUNT as COPAYAMOUNT,
  t.DEDUCTIBLEAMOUNT as DEDUCTIBLEAMOUNT,
  t.PATIENTOUTOFPOCKET as PATIENTOUTOFPOCKET,
  t.ACCESSBARRIERSCORE as ACCESSBARRIERSCORE,
  t.RISKTOLERANCESCORE as RISKTOLERANCESCORE,
  t.COMPETITORCLAIMSHARE as COMPETITORCLAIMSHARE,
  t.COVERAGEBREADTH as COVERAGEBREADTH,
  t.REIMBURSEMENTLAGDAYS as REIMBURSEMENTLAGDAYS,
  t.SOURCESYSTEM as SOURCESYSTEM
from base t
cross join anchor