select
  FORMULARYID,
  PAYER,
  PLANNAME,
  PRODUCTID,
  MARKETID,
  COVERAGESTATUS,
  FORMULARYTIER,
  PRIORAUTHREQUIRED,
  STEPTHERAPYREQUIRED,
  COPAY,
  EFFECTIVEDATE,
  EXPIRATIONDATE,
  LASTUPDATED,
  SOURCESYSTEM
from {{ ref('int_pharma__dim_payer_formulary') }}