SELECT COALESCE(SUM("SALE_PRICE"), 0) AS "TOTAL_SALE_PRICE",
    CASE
        WHEN COUNT(DISTINCT "ORDER_ID") = 0 THEN NULL
        ELSE COALESCE(COALESCE(SUM("SALE_PRICE"), 0), 0) / COUNT(DISTINCT "ORDER_ID")
    END AS "CALCULATION",
    COUNT(DISTINCT "ORDER_ID") AS "ORDER_ID_COUNT_DISTINCT"
FROM {{ref('order_items')}} AS "omni_dbt_ecomm__order_items"
WHERE "STATUS" NOT IN ('Cancelled', 'Returned') OR "STATUS" IS NULL
